# Generated by Django 6.0 on 2026-03-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelTable(
            name='socios',
            table='socios',
        ),
    ]
