# Generated by Django 6.0.3 on 2026-03-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_membresias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios',
            old_name='wsp',
            new_name='whatsapp',
        ),
    ]
