# Generated by Django 6.0.3 on 2026-03-12 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_rename_wsp_socios_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(editable=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.membresias')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='socios.socios')),
            ],
        ),
    ]
