# Generated by Django 6.0.3 on 2026-03-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_suscripciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripciones',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RenameField(
            model_name='suscripciones',
            old_name='monto_pagado',
            new_name='monto',
        ),
        migrations.AddField(
            model_name='suscripciones',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suscripciones',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_set', to='socios.socios'),
        ),
        migrations.AlterModelTable(
            name='suscripciones',
            table='Suscripciones',
        ),
    ]
