# Generated by Django 6.0.3 on 2026-03-12 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_suscripciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'Formas_Pago',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, help_text='Nro de ticket o transferencia', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.formapago')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_detalle', to='socios.suscripciones')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
            },
        ),
    ]
