# Generated by Django 6.0.3 on 2026-03-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_formapago_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gimnasio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('moneda', models.CharField(default='$', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
