# Generated by Django 6.0.3 on 2026-03-16 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_configuraciongym'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
